eureka:
    token: BND7y2ATvn78dUJyE5eA
    instance:
        hostname: localhost
    client:
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/